apiVersion: v1
data:
  CLUSTERID: bc18fe79-821c-4f9e-b794-047e46ece663
  DEFAULT_MIN_INSYNC_REPLICAS: "2"
  DEFAULT_REPLICATION_FACTOR: "3"
  NAMESPACE: dev
  NETWORK_THREAD: "3"
  REPLICAS: "3"
  SERVICE: kafka-svc
  SHARE_DIR: /mnt/kafka
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: kafka
    meta.helm.sh/release-namespace: dev
  labels:
    app.kubernetes.io/managed-by: Helm
  name: kafka-config
  namespace: dev
